---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - src/**.js
  - src/**.scss
exclude_paths:
- "docs/"
- "tests/"
- "src/example.js"
- "src/example.html"
