---
engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 60

ratings:
  paths:
  - src/**.js
  - src/**.scss
exclude_paths:
- "docs/"
- "tests/"
- "dist/"
