---
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  config:
    languages:
    - javascript
      mass_threshold: 60
ratings:
  paths:
  - src/**.js
  - src/**.scss
exclude_paths:
- "docs/"
- "tests/"
- "src/example.js"
- "src/example.html"
