---
engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
  nodesecurity:
      enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 60

ratings:
  paths:
  - src/**.js
  - src/**.scss
exclude_paths:
- "docs/"
- "tests/"
- "src/example.js"
- "src/example.html"
